/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BattleShipMainFrame.java
 *
 * Created on 01-Feb-2013, 09:07:10
 */
package uk.ac.man.cs.patterns.battleship.view;

import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import uk.ac.man.cs.patterns.battleship.utils.Constants;

/**
 *
 * @author memotoro
 */
public class BattleShipMainFrame extends javax.swing.JFrame {

    private GameListener gameListener;

    /** Creates new form BattleShipMainFrame */
    public BattleShipMainFrame() {
        initComponents();
        this.gameListener = new GameListener(this);
        this.jMenuItemManVsPc.addActionListener(this.gameListener);
    }

    /**
     * This method is called from within the constructor to
     * initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelGame = new javax.swing.JPanel();
        jMenuBarBattleShip = new javax.swing.JMenuBar();
        jMenuGame = new javax.swing.JMenu();
        jMenuItemManVsPc = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanelGameLayout = new javax.swing.GroupLayout(jPanelGame);
        jPanelGame.setLayout(jPanelGameLayout);
        jPanelGameLayout.setHorizontalGroup(
            jPanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
        jPanelGameLayout.setVerticalGroup(
            jPanelGameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        jMenuGame.setText("Game");

        jMenuItemManVsPc.setText("Man vs Pc");
        jMenuGame.add(jMenuItemManVsPc);

        jMenuBarBattleShip.add(jMenuGame);

        setJMenuBar(jMenuBarBattleShip);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelGame, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBarBattleShip;
    private javax.swing.JMenu jMenuGame;
    private javax.swing.JMenuItem jMenuItemManVsPc;
    private javax.swing.JPanel jPanelGame;
    // End of variables declaration//GEN-END:variables

    public GameListener getGameListener() {
        return gameListener;
    }

    public JMenuBar getjMenuBarBattleShip() {
        return jMenuBarBattleShip;
    }

    public JMenu getjMenuGame() {
        return jMenuGame;
    }

    public JMenuItem getjMenuItemManVsPc() {
        return jMenuItemManVsPc;
    }

    public JPanel getjPanelGame() {
        return jPanelGame;
    }
}
